<?xml version="1.0" encoding="utf-8"?> 
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup>
    <DSP_FLD>D:\AT32IDE\repo\BSP\AT32F403A_407\libraries\cmsis\dsp</DSP_FLD>
  </PropertyGroup>
  <ItemDefinitionGroup />
  <ItemGroup />
</Project>
