// clang-format off
/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode v1 to v2

    This file was automatically generated by CANopenEditor v4.2.1-0-g5ca7d71

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
*******************************************************************************/
// For CANopenNode V2 users, C macro `CO_VERSION_MAJOR=2` has to be added to project options
#ifndef CO_VERSION_MAJOR
 #include "CO_driver.h"
 #include "CO_OD.h"
 #include "CO_SDO.h"
#elif CO_VERSION_MAJOR < 4
 #include "301/CO_driver.h"
 #include "CO_OD.h"
 #include "301/CO_SDOserver.h"
#else
 #error This Object dictionary is not compatible with CANopenNode v4.0 and up!
#endif

/*******************************************************************************
   DEFINITION AND INITIALIZATION OF OBJECT DICTIONARY VARIABLES
*******************************************************************************/


/***** Definition for RAM variables *******************************************/
struct sCO_OD_RAM CO_OD_RAM = {
           CO_OD_FIRST_LAST_WORD,

/*1000*/ 0x20192L,
/*1001*/ 0x0L,
/*1003*/ {0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1005*/ 0x0080L,
/*1006*/ 0x0000L,
/*1007*/ 0x0000L,
/*1008*/ {'e', 'm', 'c', 'l'},
/*1009*/ {'S', 'e', 'e', ' ', 'P', 'C', 'B'},
/*100A*/ {'2', '.', '4', '.', '1', '3'},
/*100C*/ 0x00,
/*100D*/ 0x0L,
/*1010*/ {0x0001L, 0x0001L, 0x0001L},
/*1011*/ {0x0001L, 0x0001L, 0x0001L},
/*1014*/ 0x0080L,
/*1017*/ 0x00,
/*1018*/ {0x4L, 0x00FFL, 0x0001L, 0x0001L, 0x0000L},
/*1200*/ {{0x2L, 0x0600L, 0x0580L}},
/*1400*/ {{0x3L, 0x0200L, 0x1L, 0x00},
/*1401*/ {0x3L, 0x0300L, 0x1L, 0x00},
/*1402*/ {0x3L, 0x0400L, 0x1L, 0x00},
/*1403*/ {0x3L, 0x0500L, 0x1L, 0x00}},
/*1600*/ {{0x0L, 0x60FF0020L, 0x60400010L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1601*/ {0x0L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1602*/ {0x0L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1603*/ {0x0L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L}},
/*1800*/ {{0x5L, 0x40000180L, 0x1L, 0x3E8, 0x0L, 0x00},
/*1801*/ {0x5L, 0x40000280L, 0x1L, 0x3E8, 0x0L, 0x00},
/*1802*/ {0x5L, 0x40000380L, 0x1L, 0x3E8, 0x0L, 0x00},
/*1803*/ {0x5L, 0x40000480L, 0x1L, 0x3E8, 0x0L, 0x00}},
/*1A00*/ {{0x2L, 0x606C0020L, 0x60410010L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A01*/ {0x3L, 0x60770010L, 0x60780010L, 0x60790020L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A02*/ {0x2L, 0x60640020L, 0x20C20120L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*1A03*/ {0x0L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L}},
/*2000*/ {0x0L, 0x0L, 0x0L, 0x0L, 0x1L, 0x0L, 0x0L, 0x0L},
/*2001*/ {0x3L, 0x0L, 0x0L, 0x01},
/*200F*/ {0x0000L, 0x0000L, 0x0000L},
/*2020*/ 0x0L,
/*20C2*/ {0x0000L, 0x14C08L, 0xFFFFB1E0L},
/*2101*/ {0x0000L, 0xEA60L, 0x2EE0L},
/*2102*/ {0x3L, 0x1F40, 0xC8, 0x9L},
/*2103*/ {0x4L, 0x0L, 0x400, 0x1L, 0x0000L},
/*2290*/ 0x00,
/*2301*/ 0x4L,
/*2305*/ {0x5L, 0x0L, 0x2L, 0x00, 0x1L, 0x00},
/*2306*/ {0x3L, 0x03E8L, 0x01F4L, 0x5L},
/*2307*/ {0x1L, 0x00},
/*2308*/ {0x1L, 0x00},
/*2310*/ {0x0L, 0x0L, 0x0L},
/*2311*/ 0x1L,
/*2312*/ 0x2L,
/*2313*/ 0x0L,
/*2314*/ 0x0L,
/*2321*/ {0x3L, 0x0L, 0x0L, 0x0L},
/*2340*/ {0x00, 0x00, 0x00},
/*2341*/ {0x7FFF, 0x7FFF, 0x7FFF},
/*2342*/ {0xFFFF, 0xFFFF, 0xFFFF},
/*2343*/ {0x00, 0x00, 0x00},
/*2344*/ 0x00,
/*2345*/ 0x0L,
/*2350*/ {0x00, 0x00, 0x00},
/*2351*/ {0x7FFF, 0x7FFF, 0x7FFF},
/*2352*/ {0xFFFF, 0xFFFF, 0xFFFF},
/*2353*/ 0x00,
/*2354*/ 0x0A,
/*2360*/ {0x7L, 0x1F4, 0x190, 0x258, 0x7D0, 0x0L, 0x19L, 0x1L},
/*2361*/ {0x7L, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
/*2370*/ {0x7L, 0x00, 0xAL, 0x1L, 0x0L, 0x00, 0x0L, 0xAL},
/*2380*/ {0xAL, 0x0L, 0x19, 0x0L, 0x7D0, 0xCL, 0x0L, 0xDL, 0xCL, 0x0L, 0x10L},
/*2381*/ 0x0000L,
/*2382*/ 0x0000L,
/*2383*/ 0x0L,
/*23D0*/ {0x5L, 0x1L, 0x0000L, 0x0000L, 0x0FFFL, 0x0L},
/*23D1*/ {0x82L, 0x0L, 0xFFFFF830L, 0xFFFFF850L, 0xFFFFF86FL, 0xFFFFF88EL, 0xFFFFF8ADL, 0xFFFFF8CDL, 0xFFFFF8ECL, 0xFFFFF90BL, 0xFFFFF92AL, 0xFFFFF94AL, 0xFFFFF969L, 0xFFFFF988L, 0xFFFFF9A7L, 0xFFFFF9C7L, 0xFFFFF9E6L, 0xFFFFFA05L, 0xFFFFFA24L, 0xFFFFFA44L, 0xFFFFFA63L, 0xFFFFFA82L, 0xFFFFFAA1L, 0xFFFFFAC1L, 0xFFFFFAE0L, 0xFFFFFAFFL, 0xFFFFFB1EL, 0xFFFFFB3EL, 0xFFFFFB5DL, 0xFFFFFB7CL, 0xFFFFFB9BL, 0xFFFFFBBBL, 0xFFFFFBDAL, 0xFFFFFBF9L, 0xFFFFFC18L, 0xFFFFFC38L, 0xFFFFFC57L, 0xFFFFFC76L, 0xFFFFFC95L, 0xFFFFFCB5L, 0xFFFFFCD4L, 0xFFFFFCF3L, 0xFFFFFD12L, 0xFFFFFD32L, 0xFFFFFD51L, 0xFFFFFD70L, 0xFFFFFD8FL, 0xFFFFFDAFL, 0xFFFFFDCEL, 0xFFFFFDEDL, 0xFFFFFE0CL, 0xFFFFFE2CL, 0xFFFFFE4BL, 0xFFFFFE6AL, 0xFFFFFE89L, 0xFFFFFEA9L, 0xFFFFFEC8L, 0xFFFFFEE7L, 0xFFFFFF06L, 0xFFFFFF26L, 0xFFFFFF45L, 0xFFFFFF64L, 0xFFFFFF83L, 0xFFFFFFA3L, 0xFFFFFFC2L, 0xFFFFFFE1L, 0x0000L, 0x001FL, 0x003EL, 0x005DL, 0x007DL, 0x009CL, 0x00BBL, 0x00DAL, 0x00FAL, 0x0119L, 0x0138L, 0x0157L, 0x0177L, 0x0196L, 0x01B5L, 0x01D4L, 0x01F4L, 0x0213L, 0x0232L, 0x0251L, 0x0271L, 0x0290L, 0x02AFL, 0x02CEL, 0x02EEL, 0x030DL, 0x032CL, 0x034BL, 0x036BL, 0x038AL, 0x03A9L, 0x03C8L, 0x03E8L, 0x0407L, 0x0426L, 0x0445L, 0x0465L, 0x0484L, 0x04A3L, 0x04C2L, 0x04E2L, 0x0501L, 0x0520L, 0x053FL, 0x055FL, 0x057EL, 0x059DL, 0x05BCL, 0x05DCL, 0x05FBL, 0x061AL, 0x0639L, 0x0659L, 0x0678L, 0x0697L, 0x06B6L, 0x06D6L, 0x06F5L, 0x0714L, 0x0733L, 0x0753L, 0x0772L, 0x0791L, 0x07B0L, 0x07D0L},
/*23F0*/ {0x3L, 0x208, 0x1L, 0x800},
/*2400*/ 0x0L,
/*2430*/ 0x0L,
/*2431*/ 0x0L,
/*2432*/ {0x0001L, 0x0001L},
/*2433*/ {0x0001L, 0x0001L},
/*2434*/ {0x4L, 0x1L, 0x0000L, 0x0000L, 0x03E8L},
/*2435*/ {0x6L, 0x0L, 0x0000L, 0x0000L, 0x03E8L, 0x00, 0x00},
/*2436*/ {0x3L, 0x0L, 0x03E8L, 0x0A},
/*243A*/ 0x0000L,
/*2500*/ {0x2710L, 0x0005L, 0x9C40L, 0x0000L, 0x0000L, 0x0000L, 0x03E8L},
/*2501*/ {0x0FA0L, 0x0032L, 0x0000L, 0x186A0L, 0x0000L, 0x0001L},
/*2502*/ {0x3L, 0xBB8, 0x12C, 0x8L},
/*2503*/ {0x3L, 0xBB8, 0x12C, 0x8L},
/*2504*/ {0x2L, 0x0L, 0x64},
/*2505*/ {0x2L, 0x0L, 0x64},
/*2506*/ 0x3E8,
/*2507*/ {0x0L, 0x0L, 0x0L, 0x0L, 0x0L},
/*2508*/ 0x0A,
/*2509*/ 0x01,
/*250A*/ {0x8L, 0x3E8, 0x00, 0x00, 0x0000L, 0x00, 0x00, 0x00, 0x0000L},
/*2510*/ 0x0L,
/*2600*/ {0x00, 0x00, 0x00},
/*2601*/ {0x00, 0x00},
/*2602*/ {0x00, 0x00, 0x00},
/*2603*/ {0x00, 0x00},
/*2610*/ {0x0000L, 0x0000L, 0x0000L},
/*2611*/ {0x00, 0x00},
/*2700*/ {0x6L, 0x2L, 0x190, 0x64, 0xC8, 0x2L, 0x0L},
/*2701*/ {0x6L, 0x0320L, 0x78, 0x0001L, 0x0000L, 0x0001L, 0x0067L},
/*2702*/ {0x2L, 0x3E8, 0x3E8},
/*2A02*/ {0x2L, 0xFFFF, 0xFFFF},
/*2A03*/ {0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*2A04*/ {0x0000L, 0x0000L},
/*2A05*/ {0x6L, 0x0L, 0x00, 0x00, 0x7FF, 0x00, 0x0000L},
/*2A08*/ {0x4L, 0x0L, 0x6074L, 0x1L, 0x7FFFFFFFL},
/*2A0A*/ {0x5L, 0x0000L, 0x00, 0x00, 0x00, 0x00},
/*2A0B*/ {0x5L, 0x0000L, 0x9C4, 0x4E2, 0x9C4, 0x4E2},
/*2A10*/ {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
/*2A11*/ {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x08},
/*2C00*/ {0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*2C01*/ {0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*2C02*/ {0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*2C03*/ {0x0L, 0x0L, 0x0L},
/*2C04*/ {0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*2C05*/ {0x4L, 0x0L, 0x0L, 0x00000000L, 0x0L},
/*2C06*/ {0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*2C07*/ {0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L},
/*2C08*/ {0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L, 0x0L},
/*2C09*/ {0x3L, 0x0000L, 0x0000L, 0x0000L},
/*2C0A*/ {0x3L, 0x0L, 0x0L, 0x0L},
/*2C50*/ {0x3L, 0x0A, 0x0L, 0x0000L},
/*2C51*/ {0x7L, 0x2BC, 0x00, 0x00, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*2C52*/ {0x4L, 0x60640020L, 0x60620020L, 0x606C0020L, 0x606B0020L},
/*2C55*/ {0x6L, 0x1L, 0x6074L, 0x0000L, 0x0000L, 0x0000L, 0x0000L},
/*2D00*/ {0x2L, 0x00, 0x01},
/*2FF0*/ {0x3BL, 0x00, 0x00, 0x0L, 0x0L, 0x0000L, 0x0000L, 0x0L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0L, 0x0L, 0x0L, 0x0000L, 0x00, 0x00, 0x00, 0x0L, 0x00, 0x0L, 0x0000L, 0x0000L, 0x00, 0x0L, 0x0L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0000L, 0x0L, 0x0L, 0x0L, 0x0000L, 0x0000L, 0x0L, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0000L, 0x00, 0x00, 0x00, 0x00, 0x00},
/*2FF1*/ 0x0000L,
/*2FF2*/ 0x11D,
/*2FF3*/ 0x00,
/*2FF4*/ {0x4L, 0x0000L, 0x0000L, 0x00, 0x00},
/*2FF5*/ 0x0000L,
/*2FFD*/ 0x0L,
/*2FFE*/ 0x657669724420794DL,
/*2FFF*/ 0x0000L,
/*603F*/ 0x00,
/*6040*/ 0x00,
/*6041*/ 0x00,
/*6042*/ 0x00,
/*6043*/ 0x00,
/*6044*/ 0x00,
/*6046*/ {0x0064L, 0x05DCL},
/*6048*/ {0x2L, 0x03E8L, 0x01},
/*6049*/ {0x2L, 0x03E8L, 0x01},
/*6060*/ 0x1,
/*6061*/ 0x0,
/*6062*/ 0x0000L,
/*6063*/ 0x0000L,
/*6064*/ 0x0000L,
/*6065*/ 0xFFFFFFFFL,
/*6066*/ 0x64,
/*6067*/ 0x0064L,
/*6068*/ 0x0A,
/*6069*/ 0x0000L,
/*606B*/ 0x0000L,
/*606C*/ 0x0000L,
/*606D*/ 0x3E8,
/*606E*/ 0x0A,
/*606F*/ 0x3E8,
/*6070*/ 0x64,
/*6071*/ 0x00,
/*6072*/ 0x3E8,
/*6073*/ 0x3E8,
/*6074*/ 0x00,
/*6075*/ 0x0BB8L,
/*6076*/ 0x0136L,
/*6077*/ 0x00,
/*6078*/ 0x00,
/*6079*/ 0x0000L,
/*607A*/ 0x0000L,
/*607C*/ 0x0000L,
/*607D*/ {0x80000001L, 0x7FFFFFFFL},
/*607E*/ 0x0L,
/*607F*/ 0x186A0L,
/*6080*/ 0x30D40L,
/*6081*/ 0x186A0L,
/*6083*/ 0x186A0L,
/*6084*/ 0x186A0L,
/*6085*/ 0x30D40L,
/*6086*/ 0x00,
/*6087*/ 0x2710L,
/*6088*/ 0x00,
/*608F*/ {0x07D0L, 0x0001L},
/*6090*/ {0x07D0L, 0x0001L},
/*6091*/ {0x0001L, 0x0001L},
/*6092*/ {0x0001L, 0x0001L},
/*6098*/ 0x23,
/*6099*/ {0xC350L, 0x1388L},
/*609A*/ 0x186A0L,
/*60A8*/ 0xB50000L,
/*60A9*/ 0xB50300L,
/*60AA*/ 0xB55700L,
/*60B2*/ 0x0000L,
/*60C1*/ {0x0000L},
/*60C2*/ {0x2L, 0x1L, 0xFD},
/*60C4*/ {0x6L, 0x0010L, 0x0000L, 0x0L, 0x00, 0x4L, 0x0L},
/*60C5*/ 0x30D40L,
/*60C6*/ 0x30D40L,
/*60E0*/ 0x3E8,
/*60E1*/ 0xFC18,
/*60F4*/ 0x0000L,
/*60FA*/ 0x0000L,
/*60FC*/ 0x0000L,
/*60FD*/ 0x0000L,
/*60FE*/ {0x0000L, 0x0000L},
/*60FF*/ 0x0000L,
/*6402*/ 0x0D,
/*6502*/ 0x303EFL,

           CO_OD_FIRST_LAST_WORD,
};


/***** Definition for ROM variables *******************************************/
struct sCO_OD_ROM CO_OD_ROM = {
           CO_OD_FIRST_LAST_WORD,


           CO_OD_FIRST_LAST_WORD,
};


/***** Definition for EEPROM variables *******************************************/
struct sCO_OD_EEPROM CO_OD_EEPROM = {
           CO_OD_FIRST_LAST_WORD,


           CO_OD_FIRST_LAST_WORD,
};




/*******************************************************************************
   STRUCTURES FOR RECORD TYPE OBJECTS
*******************************************************************************/


/*0x1018*/ const CO_OD_entryRecord_t OD_record1018[5] = {
           {(void*)&CO_OD_RAM.identity.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.identity.vendorID, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.identity.productCode, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.identity.revisionNumber, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.identity.serialNumber, 0x86, 0x4 },
};

/*0x1200*/ const CO_OD_entryRecord_t OD_record1200[3] = {
           {(void*)&CO_OD_RAM.SDOServerParameter[0].numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.SDOServerParameter[0].COB_IDClientToServer, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.SDOServerParameter[0].COB_IDServerToClient, 0x86, 0x4 },
};

/*0x1400*/ const CO_OD_entryRecord_t OD_record1400[4] = {
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[0].largestSubindexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[0].COB_IdUsed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[0].transmissionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[0].inhibitTime, 0x8E, 0x2 },
};

/*0x1401*/ const CO_OD_entryRecord_t OD_record1401[4] = {
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[1].largestSubindexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[1].COB_IDUsed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[1].transmissionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[1].inhibitTime, 0x8E, 0x2 },
};

/*0x1402*/ const CO_OD_entryRecord_t OD_record1402[4] = {
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[2].largestSubindexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[2].COB_IDUsed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[2].transmissionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[2].inhibitTime, 0x8E, 0x2 },
};

/*0x1403*/ const CO_OD_entryRecord_t OD_record1403[4] = {
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[3].largestSubindexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[3].COB_IDUsed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[3].transmissionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.RPDOCommunicationParameter[3].inhibitTime, 0x8E, 0x2 },
};

/*0x1600*/ const CO_OD_entryRecord_t OD_record1600[9] = {
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].numberOfMappedObjects, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].targetVelocity, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].controlWord, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].PDOMapping3AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].PDOMapping4AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].PDOMapping5AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].PDOMapping6AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].PDOMapping7AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[0].PDOMapping8AppObject, 0x8E, 0x4 },
};

/*0x1601*/ const CO_OD_entryRecord_t OD_record1601[9] = {
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].numberOfMappedObjects, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].PDOMapping1AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].PDOMapping2AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].PDOMapping3AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].PDOMapping4AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].PDOMapping5AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].PDOMapping6AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].PDOMapping7AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[1].PDOMapping8AppObject, 0x8E, 0x4 },
};

/*0x1602*/ const CO_OD_entryRecord_t OD_record1602[9] = {
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].numberOfMappedObjects, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].PDOMapping1AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].PDOMapping2AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].PDOMapping3AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].PDOMapping4AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].PDOMapping5AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].PDOMapping6AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].PDOMapping7AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[2].PDOMapping8AppObject, 0x8E, 0x4 },
};

/*0x1603*/ const CO_OD_entryRecord_t OD_record1603[9] = {
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].numberOfMappedObjects, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].PDOMapping1AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].PDOMapping2AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].PDOMapping3AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].PDOMapping4AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].PDOMapping5AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].PDOMapping6AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].PDOMapping7AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.RPDOMappingParameter[3].PDOMapping8AppObject, 0x8E, 0x4 },
};

/*0x1800*/ const CO_OD_entryRecord_t OD_record1800[6] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].largestSubindexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].COB_IDUsed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].transmissionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].inhibitTime, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[0].eventTimer, 0x8E, 0x2 },
};

/*0x1801*/ const CO_OD_entryRecord_t OD_record1801[6] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].largestSubindexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].COB_IDUsed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].transmissionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].inhibitTime, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[1].eventTimer, 0x8E, 0x2 },
};

/*0x1802*/ const CO_OD_entryRecord_t OD_record1802[6] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].largestSubindexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].COB_IDUsed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].transmissionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].inhibitTime, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[2].eventTimer, 0x8E, 0x2 },
};

/*0x1803*/ const CO_OD_entryRecord_t OD_record1803[6] = {
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].largestSubindexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].COB_IDUsed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].transmissionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].inhibitTime, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].compatibilityEntry, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.TPDOCommunicationParameter[3].eventTimer, 0x8E, 0x2 },
};

/*0x1A00*/ const CO_OD_entryRecord_t OD_record1A00[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].numberOfMappedObjects, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].velocityActualValue, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].statusWord, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].PDOMapping3AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].PDOMapping4AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].PDOMapping5AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].PDOMapping6AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].PDOMapping7AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[0].PDOMapping8AppObject, 0x8E, 0x4 },
};

/*0x1A01*/ const CO_OD_entryRecord_t OD_record1A01[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].numberOfMappedAppObjects, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].torqueActualValue, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].currentActualValue, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].DC_LinkCircuitVoltage, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].PDOMapping4AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].PDOMapping5AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].PDOMapping6AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].PDOMapping7AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[1].PDOMapping8AppObject, 0x8E, 0x4 },
};

/*0x1A02*/ const CO_OD_entryRecord_t OD_record1A02[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].numberOfMappedAppObjects, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].positionActualValue, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].temperature, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].PDOMapping3AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].PDOMapping4AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].PDOMapping5AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].PDOMapping6AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].PDOMapping7AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[2].PDOMapping8AppObject, 0x8E, 0x4 },
};

/*0x1A03*/ const CO_OD_entryRecord_t OD_record1A03[9] = {
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].numberOfMappedAppObjects, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].PDOMapping1AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].PDOMapping2AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].PDOMapping3AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].PDOMapping4AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].PDOMapping5AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].PDOMapping6AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].PDOMapping7AppObject, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.TPDOMappingParameter[3].PDOMapping8AppObject, 0x8E, 0x4 },
};

/*0x2001*/ const CO_OD_entryRecord_t OD_record2001[4] = {
           {(void*)&CO_OD_RAM.CANopenConfiguration.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.CANopenConfiguration.nodeID, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.CANopenConfiguration.baudRate, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.CANopenConfiguration.diagnosisLevel, 0x8E, 0x2 },
};

/*0x2102*/ const CO_OD_entryRecord_t OD_record2102[4] = {
           {(void*)&CO_OD_RAM.homingExtraParameters.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.homingExtraParameters.totalHomingTimeout, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.homingExtraParameters.torqueThreshold, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.homingExtraParameters.startUpHomingSensor, 0x0E, 0x1 },
};

/*0x2103*/ const CO_OD_entryRecord_t OD_record2103[5] = {
           {(void*)&CO_OD_RAM.shuntConfiguration.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.shuntConfiguration.available, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.shuntConfiguration.dutyUsed, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.shuntConfiguration.hysteresis, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.shuntConfiguration.frequency, 0x86, 0x4 },
};

/*0x2305*/ const CO_OD_entryRecord_t OD_record2305[6] = {
           {(void*)&CO_OD_RAM.commutation.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.commutation.commutationSensor, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.commutation.initialAngleDeterminationMethod, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.commutation.actualSystemAngle, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.commutation.referenceSensor, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.commutation.commutationAngleOffset, 0x86, 0x2 },
};

/*0x2306*/ const CO_OD_entryRecord_t OD_record2306[4] = {
           {(void*)&CO_OD_RAM.forcedAlignmentMethod.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.forcedAlignmentMethod.processTime, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.forcedAlignmentMethod.processCurrent, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.forcedAlignmentMethod.processTolerance, 0x0E, 0x1 },
};

/*0x2307*/ const CO_OD_entryRecord_t OD_record2307[2] = {
           {(void*)&CO_OD_RAM.knownAlignmentMethod.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.knownAlignmentMethod.initialRotorAngle, 0x8E, 0x2 },
};

/*0x2308*/ const CO_OD_entryRecord_t OD_record2308[2] = {
           {(void*)&CO_OD_RAM.nonIncrementalAlignment.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.nonIncrementalAlignment.offsetFromPhaseA, 0x8E, 0x2 },
};

/*0x2321*/ const CO_OD_entryRecord_t OD_record2321[4] = {
           {(void*)&CO_OD_RAM.digitalHalls.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.digitalHalls.polarity, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.digitalHalls.value, 0x36, 0x1 },
           {(void*)&CO_OD_RAM.digitalHalls.hallsStepOffset, 0x0E, 0x1 },
};

/*0x2360*/ const CO_OD_entryRecord_t OD_record2360[8] = {
           {(void*)&CO_OD_RAM.SMOParameters.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.SMOParameters.lockTime, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.SMOParameters.openLoopFinalSpeed, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.SMOParameters.openLoopCurrent, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.SMOParameters.openLoopTime, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.SMOParameters.openCloseTransitionEnabled, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SMOParameters.SMO_Gain, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SMOParameters.SMO_LinearZone, 0x0E, 0x1 },
};

/*0x2361*/ const CO_OD_entryRecord_t OD_record2361[8] = {
           {(void*)&CO_OD_RAM.SMO_Results.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.SMO_Results.estimatediAlpha, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.SMO_Results.estimatediBeta, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.SMO_Results.measurediAlpha, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.SMO_Results.measurediBeta, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.SMO_Results.estimatedBEMFAlpha, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.SMO_Results.estimatedBEMFBeta, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.SMO_Results.estimatedTheta, 0xB6, 0x2 },
};

/*0x2370*/ const CO_OD_entryRecord_t OD_record2370[8] = {
           {(void*)&CO_OD_RAM.resolverParameters.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.resolverParameters.resolverAngle, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.resolverParameters.resolverTolerance, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.resolverParameters.resolverPolePairs, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.resolverParameters.resolverPolarity, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.resolverParameters.resolverAdaptedAngle, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.resolverParameters.resolverErrorCode, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.resolverParameters.resolverErrorFilter, 0x0E, 0x1 },
};

/*0x2380*/ const CO_OD_entryRecord_t OD_record2380[11] = {
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.frameType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.frameSize, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.codification, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.maxClockRate, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.singleTurnBits, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.singleTurnStartBit, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.multiTurnBits, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.multiTurnStartBit, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.endianness, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.SSI_AbsoluteEncoderConfiguration.errorFilter, 0x0E, 0x1 },
};

/*0x23D0*/ const CO_OD_entryRecord_t OD_record23D0[6] = {
           {(void*)&CO_OD_RAM.analogInputFeedback.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.analogInputFeedback.analogInputUsed, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.analogInputFeedback.analogInputMotionOffset, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedback.reserved, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedback.analogInputMotionRange, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedback.analogInputPolarity, 0x0E, 0x1 },
};

/*0x23D1*/ const CO_OD_entryRecord_t OD_record23D1[131] = {
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.correctionEnabled, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value0, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value1, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value2, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value3, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value4, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value5, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value6, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value7, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value8, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value9, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value10, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value11, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value12, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value13, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value14, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value15, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value16, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value17, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value18, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value19, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value20, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value21, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value22, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value23, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value24, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value25, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value26, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value27, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value28, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value29, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value30, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value31, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value32, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value33, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value34, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value35, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value36, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value37, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value38, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value39, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value40, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value41, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value42, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value43, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value44, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value45, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value46, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value47, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value48, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value49, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value50, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value51, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value52, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value53, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value54, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value55, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value56, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value57, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value58, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value59, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value60, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value61, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value62, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value63, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value64, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value65, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value66, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value67, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value68, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value69, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value70, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value71, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value72, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value73, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value74, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value75, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value76, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value77, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value78, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value79, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value80, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value81, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value82, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value83, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value84, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value85, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value86, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value87, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value88, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value89, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value90, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value91, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value92, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value93, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value94, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value95, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value96, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value97, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value98, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value99, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value100, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value101, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value102, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value103, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value104, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value105, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value106, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value107, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value108, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value109, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value110, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value111, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value112, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value113, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value114, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value115, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value116, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value117, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value118, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value119, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value120, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value121, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value122, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value123, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value124, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value125, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value126, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value127, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputFeedbackCorrection.value128, 0x8E, 0x4 },
};

/*0x23F0*/ const CO_OD_entryRecord_t OD_record23F0[4] = {
           {(void*)&CO_OD_RAM.DC_TachometerParameters.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.DC_TachometerParameters.voltageMVPer1000rpm, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.DC_TachometerParameters.analogInputUsed, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.DC_TachometerParameters.analogInputOffset, 0x8E, 0x2 },
};

/*0x2434*/ const CO_OD_entryRecord_t OD_record2434[5] = {
           {(void*)&CO_OD_RAM.analogInputCmdSource.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.analogInputCmdSource.analogInputUsed, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.analogInputCmdSource.analogInputMotionOffset, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputCmdSource.analogInputVelocityDeadband, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogInputCmdSource.analogInputMotionRange, 0x8E, 0x4 },
};

/*0x2435*/ const CO_OD_entryRecord_t OD_record2435[7] = {
           {(void*)&CO_OD_RAM.PWMCmdSource.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.PWMCmdSource.mode, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.PWMCmdSource.PWMInputMotionOffset, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.PWMCmdSource.PWMInputVelocityDeadband, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.PWMCmdSource.PWMInputMotionRange, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.PWMCmdSource.PWMDutyActual, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.PWMCmdSource.PWMPeriodActual, 0x86, 0x2 },
};

/*0x2436*/ const CO_OD_entryRecord_t OD_record2436[4] = {
           {(void*)&CO_OD_RAM.internalGeneratorCmdSource.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.internalGeneratorCmdSource.functionType, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.internalGeneratorCmdSource.amplitude, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.internalGeneratorCmdSource.frequency10MHz, 0x8E, 0x2 },
};

/*0x2502*/ const CO_OD_entryRecord_t OD_record2502[4] = {
           {(void*)&CO_OD_RAM.fluxControlParameterSet.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.fluxControlParameterSet.proportionalConstant, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.fluxControlParameterSet.integralConstant, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.fluxControlParameterSet.constantScaling, 0x0E, 0x1 },
};

/*0x2503*/ const CO_OD_entryRecord_t OD_record2503[4] = {
           {(void*)&CO_OD_RAM.torqueControlParameterSet.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.torqueControlParameterSet.proportionalConstant, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.torqueControlParameterSet.integralConstant, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.torqueControlParameterSet.constantScaling, 0x0E, 0x1 },
};

/*0x2504*/ const CO_OD_entryRecord_t OD_record2504[3] = {
           {(void*)&CO_OD_RAM.torqueDemandLowPassFilter.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.torqueDemandLowPassFilter.filterEnabled, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.torqueDemandLowPassFilter.cutoffFrequency, 0x8E, 0x2 },
};

/*0x2505*/ const CO_OD_entryRecord_t OD_record2505[3] = {
           {(void*)&CO_OD_RAM.torqueActualLowPassFilter.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.torqueActualLowPassFilter.filterEnabled, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.torqueActualLowPassFilter.cutoffFrequency, 0x8E, 0x2 },
};

/*0x250A*/ const CO_OD_entryRecord_t OD_record250A[9] = {
           {(void*)&CO_OD_RAM.disturbanceSignal.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.disturbanceSignal.maxEntries, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.disturbanceSignal.filledEntries, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.disturbanceSignal.entryNumber, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.disturbanceSignal.entryValue, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.disturbanceSignal.injectionPoint, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.disturbanceSignal.numberOfCycles, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.disturbanceSignal.updateRate, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.disturbanceSignal.outputValue, 0x86, 0x4 },
};

/*0x2700*/ const CO_OD_entryRecord_t OD_record2700[7] = {
           {(void*)&CO_OD_RAM.stepperParameters.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.stepperParameters.numberOfMicrostepsBits, 0x3E, 0x1 },
           {(void*)&CO_OD_RAM.stepperParameters.runCurrent, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.stepperParameters.standbyCurrent, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.stepperParameters.numberOfStepsPerRevolution, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.stepperParameters.numberOfPhases, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.stepperParameters.enhancedCurrentMode, 0x0E, 0x1 },
};

/*0x2701*/ const CO_OD_entryRecord_t OD_record2701[7] = {
           {(void*)&CO_OD_RAM.motorParameters.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.motorParameters.resistancePhaseToPhase, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.motorParameters.inductancePhaseToPhase, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.motorParameters.magneticPolePitch, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.motorParameters.motorBackemfConstantKv, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.motorParameters.strokeUm, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.motorParameters.motorTorqueConstantKm, 0x8E, 0x4 },
};

/*0x2702*/ const CO_OD_entryRecord_t OD_record2702[3] = {
           {(void*)&CO_OD_RAM.I2tParameters.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.I2tParameters.peakCurrent, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.I2tParameters.peakTime, 0x8E, 0x2 },
};

/*0x2A02*/ const CO_OD_entryRecord_t OD_record2A02[3] = {
           {(void*)&CO_OD_RAM.digitalInputsOutputs.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.digitalInputsOutputs.inputPolarity, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.digitalInputsOutputs.outputPolarity, 0x8E, 0x2 },
};

/*0x2A05*/ const CO_OD_entryRecord_t OD_record2A05[7] = {
           {(void*)&CO_OD_RAM.brakeOptions.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.brakeOptions.mode, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.brakeOptions.delayBeforeReleaseBrake, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.brakeOptions.delayAfterEnableBrake, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.brakeOptions.dutyCycle, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.brakeOptions.fullReleaseBrakePulseTime, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.brakeOptions.frequency, 0x86, 0x4 },
};

/*0x2A08*/ const CO_OD_entryRecord_t OD_record2A08[5] = {
           {(void*)&CO_OD_RAM.analogOutputAutomatic.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.analogOutputAutomatic.modeEnabled, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.analogOutputAutomatic.sourceRegister, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.analogOutputAutomatic.destinationOutput, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.analogOutputAutomatic.maxRepresentedValue, 0x8E, 0x4 },
};

/*0x2A0A*/ const CO_OD_entryRecord_t OD_record2A0A[6] = {
           {(void*)&CO_OD_RAM.PWM_Inputs.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.PWM_Inputs.maxPWMFrequency, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.PWM_Inputs.PWMPeriod1, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.PWM_Inputs.PWMDuty1, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.PWM_Inputs.PWMPeriod2, 0xB6, 0x2 },
           {(void*)&CO_OD_RAM.PWM_Inputs.PWMDuty2, 0xB6, 0x2 },
};

/*0x2A0B*/ const CO_OD_entryRecord_t OD_record2A0B[6] = {
           {(void*)&CO_OD_RAM.PWM_Outputs.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.PWM_Outputs.maxPWMFrequency, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.PWM_Outputs.PWMPeriod1, 0xBE, 0x2 },
           {(void*)&CO_OD_RAM.PWM_Outputs.PWMDuty1, 0xBE, 0x2 },
           {(void*)&CO_OD_RAM.PWM_Outputs.PWMPeriod2, 0xBE, 0x2 },
           {(void*)&CO_OD_RAM.PWM_Outputs.PWMDuty2, 0xBE, 0x2 },
};

/*0x2C05*/ const CO_OD_entryRecord_t OD_record2C05[5] = {
           {(void*)&CO_OD_RAM.macroAccess.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.macroAccess.macroNumber, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.macroAccess.macroCommand, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.macroAccess.command, 0x8E, 0x8 },
           {(void*)&CO_OD_RAM.macroAccess.unprotectedAccess, 0x0E, 0x1 },
};

/*0x2C09*/ const CO_OD_entryRecord_t OD_record2C09[4] = {
           {(void*)&CO_OD_RAM.pointerAccess.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.pointerAccess.pointerToRegister, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.pointerAccess.contentOfRegister, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.pointerAccess.writeContentToRegister, 0x8E, 0x4 },
};

/*0x2C0A*/ const CO_OD_entryRecord_t OD_record2C0A[4] = {
           {(void*)&CO_OD_RAM.macroDebug.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.macroDebug.actualMacroNumber, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.macroDebug.actualCommandNumber, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.macroDebug.macroStatus, 0x06, 0x1 },
};

/*0x2C50*/ const CO_OD_entryRecord_t OD_record2C50[4] = {
           {(void*)&CO_OD_RAM.monitorConfig.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.monitorConfig.samplingRate, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.monitorConfig.enableMode, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.monitorConfig.triggerDelayInSamples, 0x8E, 0x4 },
};

/*0x2C51*/ const CO_OD_entryRecord_t OD_record2C51[8] = {
           {(void*)&CO_OD_RAM.monitorResult.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.monitorResult.maxEntryNumber, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.monitorResult.filledEntryValues, 0x86, 0x2 },
           {(void*)&CO_OD_RAM.monitorResult.entryNumber, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.monitorResult.actualEntryTable1, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.monitorResult.actualEntryTable2, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.monitorResult.actualEntryTable3, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.monitorResult.actualEntryTable4, 0x86, 0x4 },
};

/*0x2C52*/ const CO_OD_entryRecord_t OD_record2C52[5] = {
           {(void*)&CO_OD_RAM.monitorMapping.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.monitorMapping.channel1, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.monitorMapping.channel2, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.monitorMapping.channel3, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.monitorMapping.channel4, 0x8E, 0x4 },
};

/*0x2C55*/ const CO_OD_entryRecord_t OD_record2C55[7] = {
           {(void*)&CO_OD_RAM.trigger1.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.trigger1.mode, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.trigger1.sourceRegister, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.trigger1.positiveThreshold, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.trigger1.negativeThreshold, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.trigger1.digitalInputMask, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.trigger1.delayInSamples, 0x8E, 0x4 },
};

/*0x2D00*/ const CO_OD_entryRecord_t OD_record2D00[3] = {
           {(void*)&CO_OD_RAM.openLoopParameters.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.openLoopParameters.targetVoltage, 0xBE, 0x2 },
           {(void*)&CO_OD_RAM.openLoopParameters.targetFrequency, 0xBE, 0x2 },
};

/*0x2FF0*/ const CO_OD_entryRecord_t OD_record2FF0[60] = {
           {(void*)&CO_OD_RAM.hardwareConfiguration.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.currentSensingResistorValue, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.preamplifierGain, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.VGAAvailable, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.temperatureSensorAvailable, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.maxAbsoluteTemperatureMC, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.minAbsoluteTemperatureMC, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.vbusSensorAvailable, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.maxAbsoluteVoltageMV, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.minAbsoluteVoltageMV, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.nominalCurrentMA_RMSValue, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.peakCurrentMA_RMSValue, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.maximumPeakTime100us, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.maximumCurrentMAPeakValue, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.stepperIn3phasesAvailable, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.NVMAvailable, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.HWErrorAvailable, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.temperatureSensorOffsetMV, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.temperatureSensorGainMV_C, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.vbusSensorGain, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.deadtimeNs, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.PWMFrequencyScaleLegacy, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.boostrapChargeTimeMs, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.NTCSensorAvailable, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.NTC_RextOhm, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.NTC_R25Ohm, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.NTC_B25K, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.resolverAvailable, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.nodeIDByHW, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.PWMFrequencyHz, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.availableDigitalInputs, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.availableDigitalOutputs, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.availableAnalogInputs, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.availableAnalogOutputs, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.commercialProductID, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.commercialSerialNumber, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.2PhasesSwitchingScheme, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.driverEnableInUARTCom, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.availableCurrentSensors, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.digitalInputsPolarityMask, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.digitalOutputsPolarityMask, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.analogReferenceVoltage, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.analogInput12Parameters, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.analogInput34Parameters, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.analogOutput12Parameters, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.macroParameters, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.supportedMotorTypes, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.supportedCommunicationInterfaces, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.supportedFeedbacks, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.PWMMaximumDutyCycle, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.currentLoopFrequency, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.positionVelocityLoopFrequency, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.supportedCommandSource, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.safeTorqueOffInput, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.alternativeFrequencyPWM_Hz, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.currentLowPassFilterOutput, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.analogInput5Parameters, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.openLoadProtectionInput, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.shuntOutput, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.hardwareConfiguration.brakeOutput, 0x8E, 0x2 },
};

/*0x2FF4*/ const CO_OD_entryRecord_t OD_record2FF4[5] = {
           {(void*)&CO_OD_RAM.HWIdentification.numberOfEntries, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.HWIdentification.HW_Version, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.HWIdentification.HW_Variant, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.HWIdentification.HWProgrammingDate, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.HWIdentification.HWConfigurationRevision, 0x8E, 0x2 },
};

/*0x6048*/ const CO_OD_entryRecord_t OD_record6048[3] = {
           {(void*)&CO_OD_RAM.vlVelocityAcceleration.highestSubIndexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.vlVelocityAcceleration.deltaSpeed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.vlVelocityAcceleration.deltaTime, 0x8E, 0x2 },
};

/*0x6049*/ const CO_OD_entryRecord_t OD_record6049[3] = {
           {(void*)&CO_OD_RAM.vlVelocityDeceleration.highestSubIndexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.vlVelocityDeceleration.deltaSpeed, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.vlVelocityDeceleration.deltaTime, 0x8E, 0x2 },
};

/*0x60C2*/ const CO_OD_entryRecord_t OD_record60C2[3] = {
           {(void*)&CO_OD_RAM.interpolationTimePeriod.highestSubIndexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.interpolationTimePeriod.interpolationTimePeriodValue, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.interpolationTimePeriod.interpolationTimeIndex, 0x0E, 0x1 },
};

/*0x60C4*/ const CO_OD_entryRecord_t OD_record60C4[7] = {
           {(void*)&CO_OD_RAM.interpolationDataConfiguration.highestSubIndexSupported, 0x06, 0x1 },
           {(void*)&CO_OD_RAM.interpolationDataConfiguration.maximumBufferSize, 0x86, 0x4 },
           {(void*)&CO_OD_RAM.interpolationDataConfiguration.actualBufferSize, 0x8E, 0x4 },
           {(void*)&CO_OD_RAM.interpolationDataConfiguration.bufferOrganisation, 0x0E, 0x1 },
           {(void*)&CO_OD_RAM.interpolationDataConfiguration.bufferPosition, 0x8E, 0x2 },
           {(void*)&CO_OD_RAM.interpolationDataConfiguration.sizeOfDataRecord, 0x0A, 0x1 },
           {(void*)&CO_OD_RAM.interpolationDataConfiguration.bufferClear, 0x0A, 0x1 },
};

/*******************************************************************************
   OBJECT DICTIONARY
*******************************************************************************/
const CO_OD_entry_t CO_OD[CO_OD_NoOfElements] = {
{0x1000, 0x00, 0x86,  4, (void*)&CO_OD_RAM.deviceType},
{0x1001, 0x00, 0x06,  1, (void*)&CO_OD_RAM.errorRegister},
{0x1003, 0x04, 0x0A,  0, (void*)&CO_OD_RAM.preDefinedErrorField[0]},
{0x1005, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.COB_ID_SYNCMessage},
{0x1006, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.cyclePeriod},
{0x1007, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.syncWindowsLength},
{0x1008, 0x00, 0x06,  4, (void*)&CO_OD_RAM.deviceName},
{0x1009, 0x00, 0x06,  7, (void*)&CO_OD_RAM.hardwareVersion},
{0x100A, 0x00, 0x06,  6, (void*)&CO_OD_RAM.softwareVersion},
{0x100C, 0x00, 0x8E,  2, (void*)&CO_OD_RAM.guardTime},
{0x100D, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.lifeTimeFactor},
{0x1010, 0x03, 0x02,  0, (void*)&CO_OD_RAM.storeParameters[0]},
{0x1011, 0x03, 0x02,  0, (void*)&CO_OD_RAM.restoreDefaultParameters[0]},
{0x1014, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.COB_ID_EmergencyMessage},
{0x1017, 0x00, 0x8E,  2, (void*)&CO_OD_RAM.producerHeartbeatTime},
{0x1018, 0x04, 0x00,  0, (void*)&OD_record1018},
{0x1200, 0x02, 0x00,  0, (void*)&OD_record1200},
{0x1400, 0x03, 0x00,  0, (void*)&OD_record1400},
{0x1401, 0x03, 0x00,  0, (void*)&OD_record1401},
{0x1402, 0x03, 0x00,  0, (void*)&OD_record1402},
{0x1403, 0x03, 0x00,  0, (void*)&OD_record1403},
{0x1600, 0x08, 0x00,  0, (void*)&OD_record1600},
{0x1601, 0x08, 0x00,  0, (void*)&OD_record1601},
{0x1602, 0x08, 0x00,  0, (void*)&OD_record1602},
{0x1603, 0x08, 0x00,  0, (void*)&OD_record1603},
{0x1800, 0x05, 0x00,  0, (void*)&OD_record1800},
{0x1801, 0x05, 0x00,  0, (void*)&OD_record1801},
{0x1802, 0x05, 0x00,  0, (void*)&OD_record1802},
{0x1803, 0x05, 0x00,  0, (void*)&OD_record1803},
{0x1A00, 0x08, 0x00,  0, (void*)&OD_record1A00},
{0x1A01, 0x08, 0x00,  0, (void*)&OD_record1A01},
{0x1A02, 0x08, 0x00,  0, (void*)&OD_record1A02},
{0x1A03, 0x08, 0x00,  0, (void*)&OD_record1A03},
{0x2000, 0x08, 0x02,  0, (void*)&CO_OD_RAM.uartConfiguration[0]},
{0x2001, 0x03, 0x00,  0, (void*)&OD_record2001},
{0x200F, 0x03, 0x02,  0, (void*)&CO_OD_RAM.communicationPassword[0]},
{0x2020, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.enableAlternativeFrequencyPWM},
{0x20C2, 0x03, 0x02,  0, (void*)&CO_OD_RAM.driverTemperature[0]},
{0x2101, 0x03, 0x02,  0, (void*)&CO_OD_RAM.busVoltage[0]},
{0x2102, 0x03, 0x00,  0, (void*)&OD_record2102},
{0x2103, 0x04, 0x00,  0, (void*)&OD_record2103},
{0x2290, 0x00, 0x8E,  2, (void*)&CO_OD_RAM.driveSetupStatus},
{0x2301, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.motorPairPoles},
{0x2305, 0x05, 0x00,  0, (void*)&OD_record2305},
{0x2306, 0x03, 0x00,  0, (void*)&OD_record2306},
{0x2307, 0x01, 0x00,  0, (void*)&OD_record2307},
{0x2308, 0x01, 0x00,  0, (void*)&OD_record2308},
{0x2310, 0x03, 0x02,  0, (void*)&CO_OD_RAM.feedbacks[0]},
{0x2311, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.digEncoderSinCosPolarity},
{0x2312, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.digEncoderSinCosType},
{0x2313, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.digEncoderSinCosGlitchFilter},
{0x2314, 0x00, 0x36,  1, (void*)&CO_OD_RAM.digEncoderValue},
{0x2321, 0x03, 0x00,  0, (void*)&OD_record2321},
{0x2340, 0x03, 0x02,  0, (void*)&CO_OD_RAM.linearHallValues[0]},
{0x2341, 0x03, 0x02,  0, (void*)&CO_OD_RAM.linearHallOffsets[0]},
{0x2342, 0x03, 0x02,  0, (void*)&CO_OD_RAM.linearHallGains[0]},
{0x2343, 0x03, 0x02,  0, (void*)&CO_OD_RAM.linearHallRotational[0]},
{0x2344, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.linearHallEstimatedAngle},
{0x2345, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.linearHallPolarity},
{0x2350, 0x03, 0x02,  0, (void*)&CO_OD_RAM.sinCosValues[0]},
{0x2351, 0x03, 0x02,  0, (void*)&CO_OD_RAM.sinCosOffsets[0]},
{0x2352, 0x03, 0x02,  0, (void*)&CO_OD_RAM.sinCosGains[0]},
{0x2353, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.sinCosEstimatedAngle},
{0x2354, 0x00, 0x8E,  2, (void*)&CO_OD_RAM.sinCosMultiplierFactor},
{0x2360, 0x07, 0x00,  0, (void*)&OD_record2360},
{0x2361, 0x07, 0x00,  0, (void*)&OD_record2361},
{0x2370, 0x07, 0x00,  0, (void*)&OD_record2370},
{0x2380, 0x0A, 0x00,  0, (void*)&OD_record2380},
{0x2381, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.SSIMultiTurnValue},
{0x2382, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.SSISingleTurnValue},
{0x2383, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.SSIPolarity},
{0x23D0, 0x05, 0x00,  0, (void*)&OD_record23D0},
{0x23D1, 0x82, 0x00,  0, (void*)&OD_record23D1},
{0x23F0, 0x03, 0x00,  0, (void*)&OD_record23F0},
{0x2400, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.systemPolarity},
{0x2430, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.commandReferenceSource},
{0x2431, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.localRemoteControl},
{0x2432, 0x02, 0x02,  0, (void*)&CO_OD_RAM.electronicGearingCmdSource[0]},
{0x2433, 0x02, 0x02,  0, (void*)&CO_OD_RAM.stepAndDirectionCmdSource[0]},
{0x2434, 0x04, 0x00,  0, (void*)&OD_record2434},
{0x2435, 0x06, 0x00,  0, (void*)&OD_record2435},
{0x2436, 0x03, 0x00,  0, (void*)&OD_record2436},
{0x243A, 0x00, 0x86,  4, (void*)&CO_OD_RAM.internalTargetCmdSource},
{0x2500, 0x07, 0x02,  0, (void*)&CO_OD_RAM.positionControlParameterSet[0]},
{0x2501, 0x06, 0x02,  0, (void*)&CO_OD_RAM.velocityControlParameterSet[0]},
{0x2502, 0x03, 0x00,  0, (void*)&OD_record2502},
{0x2503, 0x03, 0x00,  0, (void*)&OD_record2503},
{0x2504, 0x02, 0x00,  0, (void*)&OD_record2504},
{0x2505, 0x02, 0x00,  0, (void*)&OD_record2505},
{0x2506, 0x00, 0x8E,  2, (void*)&CO_OD_RAM.maxTorqueCteSpeed},
{0x2507, 0x05, 0x02,  0, (void*)&CO_OD_RAM.controlLoopsConfiguration[0]},
{0x2508, 0x00, 0x8E,  2, (void*)&CO_OD_RAM.torqueWindow},
{0x2509, 0x00, 0x8E,  2, (void*)&CO_OD_RAM.torqueWindowTime},
{0x250A, 0x08, 0x00,  0, (void*)&OD_record250A},
{0x2510, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.enableCurrentLowPassFilter},
{0x2600, 0x03, 0x02,  0, (void*)&CO_OD_RAM.currentReadings[0]},
{0x2601, 0x02, 0x02,  0, (void*)&CO_OD_RAM.currentdq[0]},
{0x2602, 0x03, 0x02,  0, (void*)&CO_OD_RAM.currentReadingsThousands[0]},
{0x2603, 0x02, 0x02,  0, (void*)&CO_OD_RAM.currentDemandSteppers[0]},
{0x2610, 0x03, 0x02,  0, (void*)&CO_OD_RAM.voltageGenerated[0]},
{0x2611, 0x02, 0x02,  0, (void*)&CO_OD_RAM.voltagedq[0]},
{0x2700, 0x06, 0x00,  0, (void*)&OD_record2700},
{0x2701, 0x06, 0x00,  0, (void*)&OD_record2701},
{0x2702, 0x02, 0x00,  0, (void*)&OD_record2702},
{0x2A02, 0x02, 0x00,  0, (void*)&OD_record2A02},
{0x2A03, 0x08, 0x02,  0, (void*)&CO_OD_RAM.analogInputs[0]},
{0x2A04, 0x02, 0x02,  0, (void*)&CO_OD_RAM.analogOutput[0]},
{0x2A05, 0x06, 0x00,  0, (void*)&OD_record2A05},
{0x2A08, 0x04, 0x00,  0, (void*)&OD_record2A08},
{0x2A0A, 0x05, 0x00,  0, (void*)&OD_record2A0A},
{0x2A0B, 0x05, 0x00,  0, (void*)&OD_record2A0B},
{0x2A10, 0x0A, 0x02,  0, (void*)&CO_OD_RAM.GPIMappingParameter[0]},
{0x2A11, 0x0A, 0x02,  0, (void*)&CO_OD_RAM.GPOMappingParameter[0]},
{0x2C00, 0x64, 0x02,  0, (void*)&CO_OD_RAM.generalPurposeRegisters[0]},
{0x2C01, 0x17, 0x02,  0, (void*)&CO_OD_RAM.registerCommands[0]},
{0x2C02, 0x17, 0x02,  0, (void*)&CO_OD_RAM.sequenceCommands[0]},
{0x2C03, 0x03, 0x02,  0, (void*)&CO_OD_RAM.learnedPosition[0]},
{0x2C04, 0x08, 0x02,  0, (void*)&CO_OD_RAM.macroCommands[0]},
{0x2C05, 0x04, 0x00,  0, (void*)&OD_record2C05},
{0x2C06, 0x04, 0x02,  0, (void*)&CO_OD_RAM.timersAccess[0]},
{0x2C07, 0x0C, 0x02,  0, (void*)&CO_OD_RAM.interruptVector[0]},
{0x2C08, 0x0C, 0x02,  0, (void*)&CO_OD_RAM.interruptEnable[0]},
{0x2C09, 0x03, 0x00,  0, (void*)&OD_record2C09},
{0x2C0A, 0x03, 0x00,  0, (void*)&OD_record2C0A},
{0x2C50, 0x03, 0x00,  0, (void*)&OD_record2C50},
{0x2C51, 0x07, 0x00,  0, (void*)&OD_record2C51},
{0x2C52, 0x04, 0x00,  0, (void*)&OD_record2C52},
{0x2C55, 0x06, 0x00,  0, (void*)&OD_record2C55},
{0x2D00, 0x02, 0x00,  0, (void*)&OD_record2D00},
{0x2FF0, 0x3B, 0x00,  0, (void*)&OD_record2FF0},
{0x2FF1, 0x00, 0x8A,  4, (void*)&CO_OD_RAM.hardwareConfigurationPass},
{0x2FF2, 0x00, 0x86,  2, (void*)&CO_OD_RAM.EDSVersion},
{0x2FF3, 0x00, 0x8E,  2, (void*)&CO_OD_RAM.HWAvailableRegisters},
{0x2FF4, 0x04, 0x00,  0, (void*)&OD_record2FF4},
{0x2FF5, 0x00, 0x86,  4, (void*)&CO_OD_RAM.buildNumber},
{0x2FFD, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.maximumCurrentRange},
{0x2FFE, 0x00, 0x8E,  8, (void*)&CO_OD_RAM.driveName},
{0x2FFF, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.resetDevice},
{0x603F, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.errorCode},
{0x6040, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.controlword},
{0x6041, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.statusword},
{0x6042, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.vlTargetVelocity},
{0x6043, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.vlVelocityDemand},
{0x6044, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.vlVelocityActualValue},
{0x6046, 0x02, 0x02,  0, (void*)&CO_OD_RAM.vlVelocityMinMaxAmount[0]},
{0x6048, 0x02, 0x00,  0, (void*)&OD_record6048},
{0x6049, 0x02, 0x00,  0, (void*)&OD_record6049},
{0x6060, 0x00, 0x3E,  1, (void*)&CO_OD_RAM.modesOfOperation},
{0x6061, 0x00, 0x36,  1, (void*)&CO_OD_RAM.modesOfOperationDisplay},
{0x6062, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.positionDemandValue},
{0x6063, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.positionActualInternalValue},
{0x6064, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.positionActualValue},
{0x6065, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.followingErrorWindow},
{0x6066, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.followingErrorTimeOut},
{0x6067, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.positionWindow},
{0x6068, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.positionWindowTime},
{0x6069, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.velocitySensorActualValue},
{0x606B, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.velocityDemandValue},
{0x606C, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.velocityActualValue},
{0x606D, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.velocityWindow},
{0x606E, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.velocityWindowTime},
{0x606F, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.velocityThreshold},
{0x6070, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.velocityThresholdTime},
{0x6071, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.targetTorque},
{0x6072, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.maxTorque},
{0x6073, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.maxCurrent},
{0x6074, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.torqueDemand},
{0x6075, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.motorRatedCurrent},
{0x6076, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.motorRatedTorque},
{0x6077, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.torqueActualValue},
{0x6078, 0x00, 0xB6,  2, (void*)&CO_OD_RAM.currentActualValue},
{0x6079, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.DCLinkCircuitVoltage},
{0x607A, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.targetPosition},
{0x607C, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.homeOffset},
{0x607D, 0x02, 0x02,  0, (void*)&CO_OD_RAM.softwarePositionLimit[0]},
{0x607E, 0x00, 0x3E,  1, (void*)&CO_OD_RAM.polarity},
{0x607F, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.maxProfileVelocity},
{0x6080, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.maxMotorSpeed},
{0x6081, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.profileVelocity},
{0x6083, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.profileAcceleration},
{0x6084, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.profileDeceleration},
{0x6085, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.quickStopDeceleration},
{0x6086, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.motionProfileType},
{0x6087, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.torqueSlope},
{0x6088, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.torqueProfileType},
{0x608F, 0x02, 0x02,  0, (void*)&CO_OD_RAM.positionEncoderResolution[0]},
{0x6090, 0x02, 0x02,  0, (void*)&CO_OD_RAM.velocityEncoderResolution[0]},
{0x6091, 0x02, 0x02,  0, (void*)&CO_OD_RAM.gearRatio[0]},
{0x6092, 0x02, 0x02,  0, (void*)&CO_OD_RAM.feedConstant[0]},
{0x6098, 0x00, 0x0E,  1, (void*)&CO_OD_RAM.homingMethod},
{0x6099, 0x02, 0x02,  0, (void*)&CO_OD_RAM.homingSpeeds[0]},
{0x609A, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.homingAcceleration},
{0x60A8, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.SIUnitPosition},
{0x60A9, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.SIUnitVelocity},
{0x60AA, 0x00, 0x8E,  4, (void*)&CO_OD_RAM.SIUnitAcceleration},
{0x60B2, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.torqueOffset},
{0x60C1, 0x01, 0x02,  0, (void*)&CO_OD_RAM.interpolationDataRecord[0]},
{0x60C2, 0x02, 0x00,  0, (void*)&OD_record60C2},
{0x60C4, 0x06, 0x00,  0, (void*)&OD_record60C4},
{0x60C5, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.maxAcceleration},
{0x60C6, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.maxDeceleration},
{0x60E0, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.positiveTorqueLimitValue},
{0x60E1, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.negativeTorqueLimitValue},
{0x60F4, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.followingErrorActualValue},
{0x60FA, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.controlEffort},
{0x60FC, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.positionDemandInternalValue},
{0x60FD, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.digitalInputs},
{0x60FE, 0x02, 0x02,  0, (void*)&CO_OD_RAM.digitalOutputs[0]},
{0x60FF, 0x00, 0xBE,  4, (void*)&CO_OD_RAM.targetVelocity},
{0x6402, 0x00, 0xBE,  2, (void*)&CO_OD_RAM.motorType},
{0x6502, 0x00, 0xB6,  4, (void*)&CO_OD_RAM.supportedDriveModes},
};
// clang-format on
